#!/bin/bash
echo "Creating Satellite Bundle"
rm -rf satellite_bundle
git clone --depth 1 git://github.com/davidtrem/Satellite.git satellite_bundle
git clone --depth 1 git://github.com/davidtrem/ThunderStorm.git
mv ThunderStorm/thunderstorm satellite_bundle
rm -rf ThunderStorm
zip -r9 satellite_bundle.zip satellite_bundle/
cp msdll/* satellite_bundle